begin;
create extension if not exists pgtap with schema extensions;
select plan(29);
select has_table('public','chat_attachment_upload_slots','upload slots exist');
select has_column('public','chat_attachment_upload_slots','expires_at','upload slot expires');
select has_column('public','chat_attachment_upload_slots','consumed_at','upload slot is idempotently consumed');
select has_function('public','create_chat_attachment_upload_slot',array['uuid','uuid','text','text','bigint','integer','integer','text'],'server-authorized upload slot RPC exists');
select function_privs_are('public','create_chat_attachment_upload_slot',array['uuid','uuid','text','text','bigint','integer','integer','text'],'anon',array[]::text[],'anon cannot create upload slots');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='chat_attachment_upload_slots'),'upload slot RLS enabled');
select table_privs_are('public','chat_attachment_upload_slots','anon',array[]::text[],'anon has no upload slot privileges');
select has_table('public','message_attachments','message attachments exist');
select has_column('public','message_attachments','storage_path','attachment has Storage path');
select has_column('public','message_attachments','sha256','attachment has checksum');
select has_column('public','message_attachments','deleted_at','attachment has retention tombstone');
select col_is_pk('public','message_attachments','id','attachment UUID is primary key');
select col_is_unique('public','message_attachments','storage_path','Storage path is unique');
select col_is_fk('public','message_attachments','message_id','attachment references message');
select col_is_fk('public','message_attachments','conversation_id','attachment references conversation');
select col_is_fk('public','message_attachments','uploader_id','attachment references uploader');
select has_function('public','send_direct_message_with_attachments',array['uuid','text','uuid','uuid','jsonb'],'atomic attachment send RPC exists');
select has_function('public','get_chat_attachment_usage',array[]::text[],'attachment quota RPC exists');
select has_function('public','chat_attachment_cleanup_candidates',array[]::text[],'cleanup candidate RPC exists');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='message_attachments'),'attachment RLS enabled');
select table_privs_are('public','message_attachments','anon',array[]::text[],'anon has no attachment table privileges');
select function_privs_are('public','send_direct_message_with_attachments',array['uuid','text','uuid','uuid','jsonb'],'anon',array[]::text[],'anon cannot register attachments');
select function_privs_are('public','get_chat_attachment_usage',array[]::text[],'anon',array[]::text[],'anon cannot read quota');
select function_privs_are('public','chat_attachment_cleanup_candidates',array[]::text[],'authenticated',array[]::text[],'desktop cannot call cleanup candidates');
select results_eq($$select count(*)::bigint from storage.buckets where id='chat-attachments' and public=false$$,array[1::bigint],'chat bucket is private');
select results_eq($$select file_size_limit::bigint from storage.buckets where id='chat-attachments'$$,array[10485760::bigint],'bucket limit is 10 MB');
select results_eq($$select count(*)::bigint from pg_policies where schemaname='storage' and tablename='objects' and policyname like 'chat_attachments_%'$$,array[4::bigint],'four private Storage policies exist');
select has_trigger('public','messages','messages_soft_delete_attachments','message delete tombstones attachments');
select isnt_empty($$select 1 from pg_indexes where schemaname='public' and indexname='message_attachments_cleanup'$$,'cleanup index exists');
select * from finish();
rollback;
