begin;
create extension if not exists pgtap with schema extensions;
select plan(40);
select has_column('public','online_guilds','disbanded_at','Guild has disband state');
select has_column('public','online_guild_members','last_read_at','Guild member has read cursor');
select has_column('public','online_guild_members','contribution_points','Guild member has contribution total');
select has_column('public','online_guild_messages','reply_to_id','Guild chat supports reply');
select has_column('public','online_guild_messages','edited_at','Guild chat supports edit');
select has_column('public','online_guild_battles','end_at','Guild boss has server expiry');
select has_table('public','online_guild_bans','Guild bans exist');
select has_table('public','online_guild_message_reactions','Guild chat reactions exist');
select has_table('public','online_guild_boss_rewards','Guild boss rewards exist');
select col_is_pk('public','online_guild_bans',array['guild_id','user_id'],'Guild ban is idempotent');
select col_is_pk('public','online_guild_message_reactions',array['message_id','user_id'],'one Guild reaction per user');
select col_is_pk('public','online_guild_boss_rewards',array['battle_id','user_id'],'one Guild reward per battle/user');
select has_function('public','cancel_online_guild_join',array['uuid'],'cancel join RPC');
select has_function('public','leave_online_guild',array['uuid'],'leave Guild RPC');
select has_function('public','kick_online_guild_member',array['uuid','uuid'],'kick RPC');
select has_function('public','ban_online_guild_member',array['uuid','uuid','text'],'ban RPC');
select has_function('public','unban_online_guild_member',array['uuid','uuid'],'unban RPC');
select has_function('public','set_online_guild_role',array['uuid','uuid','text'],'role RPC');
select has_function('public','transfer_online_guild_leader',array['uuid','uuid'],'leader transfer RPC');
select has_function('public','disband_online_guild',array['uuid'],'disband RPC');
select has_function('public','update_online_guild_description',array['uuid','text'],'description RPC');
select has_function('public','send_online_guild_message_v2',array['uuid','text','uuid','uuid'],'Guild reply send RPC');
select has_function('public','edit_online_guild_message',array['uuid','text'],'Guild edit RPC');
select has_function('public','delete_online_guild_message',array['uuid'],'Guild delete/moderation RPC');
select has_function('public','set_online_guild_message_reaction',array['uuid','text'],'Guild reaction RPC');
select has_function('public','mark_online_guild_read',array['uuid'],'Guild read cursor RPC');
select has_function('public','get_my_online_guild_summary',array[]::text[],'Guild unread summary RPC');
select has_function('public','start_online_guild_boss_v2',array['uuid','text'],'server catalog boss RPC');
select has_function('public','claim_online_guild_boss_reward',array['uuid'],'boss reward claim RPC');
select has_function('public','run_online_guild_maintenance',array[]::text[],'Guild maintenance RPC');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='online_guild_bans'),'ban RLS enabled');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='online_guild_message_reactions'),'Guild reaction RLS enabled');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='online_guild_boss_rewards'),'Guild reward RLS enabled');
select table_privs_are('public','online_guild_bans','anon',array[]::text[],'anon cannot read bans');
select function_privs_are('public','kick_online_guild_member',array['uuid','uuid'],'anon',array[]::text[],'anon cannot kick');
select function_privs_are('public','transfer_online_guild_leader',array['uuid','uuid'],'anon',array[]::text[],'anon cannot transfer leader');
select function_privs_are('public','start_online_guild_boss_v2',array['uuid','text'],'anon',array[]::text[],'anon cannot start boss');
select function_privs_are('public','start_online_guild_boss',array['uuid','text','text','bigint'],'authenticated',array[]::text[],'desktop cannot supply boss HP');
select function_privs_are('public','claim_online_guild_boss_reward',array['uuid'],'anon',array[]::text[],'anon cannot claim reward');
select function_privs_are('public','run_online_guild_maintenance',array[]::text[],'anon',array[]::text[],'anon cannot run Guild maintenance');
select * from finish();rollback;
