begin;
create extension if not exists pgtap with schema extensions;
select plan(36);

select has_table('public','love_space_shared_profiles','shared Love profile exists');
select has_table('public','love_space_events','shared events exist');
select has_table('public','love_space_memories','shared memories exist');
select has_table('public','love_space_checkins','shared check-ins exist');
select has_table('public','love_space_prompt_responses','shared prompt responses exist');
select has_table('public','love_space_prompt_favorites','prompt favorites exist');
select has_table('public','love_space_weekly_reviews','weekly reviews exist');
select has_table('public','love_space_bucket_items','bucket items exist');
select has_table('public','love_space_cycle_settings','cycle settings exist');
select has_table('public','love_space_cycles','cycle logs exist');
select has_function('public','save_love_space_shared_profile',array['uuid','text','text','integer','text','date'],'profile RPC exists');
select has_function('public','save_love_space_cycle_settings',array['uuid','text','date','integer','integer'],'cycle settings RPC exists');
select has_function('public','upsert_love_space_record',array['uuid','text','uuid','jsonb'],'record upsert RPC exists');
select has_function('public','delete_love_space_record',array['uuid','text','uuid'],'record delete RPC exists');
select has_function('public','toggle_love_space_bucket_item',array['uuid','uuid','boolean'],'bucket toggle RPC exists');
select has_function('public','toggle_love_space_prompt_favorite',array['uuid','text'],'favorite toggle RPC exists');
select has_function('public','set_love_space_prompt_favorite',array['uuid','text','boolean'],'idempotent favorite RPC exists');
select col_is_pk('public','love_space_shared_profiles','love_space_id','one shared profile per Love Space');
select col_is_unique('public','love_space_checkins',array['love_space_id','created_by','checkin_date'],'one check-in per member/day');
select col_is_unique('public','love_space_weekly_reviews',array['love_space_id','created_by','week_start'],'one weekly review per member/week');
select col_is_unique('public','love_space_prompt_favorites',array['love_space_id','created_by','prompt_key'],'favorites are idempotent');
select ok((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='love_space_shared_profiles'),'profile RLS enabled');
select ok((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='love_space_events'),'events RLS enabled');
select ok((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='love_space_memories'),'memories RLS enabled');
select ok((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='love_space_checkins'),'check-ins RLS enabled');
select ok((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='love_space_prompt_responses'),'prompts RLS enabled');
select ok((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='love_space_weekly_reviews'),'reviews RLS enabled');
select ok((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='love_space_bucket_items'),'bucket RLS enabled');
select ok((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='love_space_cycle_settings'),'cycle settings RLS enabled');
select ok((select c.relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='love_space_cycles'),'cycles RLS enabled');
select table_privs_are('public','love_space_events','anon',array[]::text[],'anon has no event privileges');
select table_privs_are('public','love_space_checkins','anon',array[]::text[],'anon has no check-in privileges');
select function_privs_are('public','upsert_love_space_record',array['uuid','text','uuid','jsonb'],'anon',array[]::text[],'anon cannot upsert Love records');
select function_privs_are('public','delete_love_space_record',array['uuid','text','uuid'],'anon',array[]::text[],'anon cannot delete Love records');
select function_privs_are('public','save_love_space_shared_profile',array['uuid','text','text','integer','text','date'],'anon',array[]::text[],'anon cannot save shared profile');
select function_privs_are('public','save_love_space_cycle_settings',array['uuid','text','date','integer','integer'],'anon',array[]::text[],'anon cannot save cycle settings');

select * from finish();
rollback;
