begin;
create extension if not exists pgtap with schema extensions;
select plan(25);
select has_table('public','notification_preferences','notification preferences exist');
select col_is_pk('public','notification_preferences','user_id','one preference row per user');
select has_function('public','get_social_notifications_page',array['integer','timestamp with time zone','text'],'notification pagination RPC');
select has_function('public','mark_social_notification_read',array['uuid'],'single notification read RPC');
select has_function('public','set_notification_preferences',array['jsonb'],'notification preference RPC');
select has_function('public','rename_cloud_device',array['uuid','text'],'device rename RPC');
select has_function('public','revoke_other_cloud_devices',array['uuid'],'revoke other devices RPC');
select ok((select relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='notification_preferences'),'preferences RLS enabled');
select table_privs_are('public','notification_preferences','anon',array[]::text[],'anon has no preference privileges');
select function_privs_are('public','get_social_notifications_page',array['integer','timestamp with time zone','text'],'anon',array[]::text[],'anon cannot page notifications');
select function_privs_are('public','mark_social_notification_read',array['uuid'],'anon',array[]::text[],'anon cannot mark notifications');
select function_privs_are('public','rename_cloud_device',array['uuid','text'],'anon',array[]::text[],'anon cannot rename device');
select function_privs_are('public','revoke_other_cloud_devices',array['uuid'],'anon',array[]::text[],'anon cannot revoke devices');
select function_privs_are('public','send_direct_message',array['uuid','text','uuid'],'authenticated',array[]::text[],'legacy direct send revoked');
select function_privs_are('public','send_online_guild_message',array['uuid','text','uuid'],'authenticated',array[]::text[],'legacy Guild send revoked');
select function_privs_are('public','send_direct_message_v2',array['uuid','text','uuid','uuid'],'authenticated',array['EXECUTE'],'authenticated can send validated direct message');
select function_privs_are('public','send_online_guild_message_v2',array['uuid','text','uuid','uuid'],'authenticated',array['EXECUTE'],'authenticated can send validated Guild message');
select has_trigger('public','cloud_devices','cloud_device_security_notification','device security notification trigger exists');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='notification_preferences' and policyname='notification_preferences_owner_read'),'owner preference policy exists');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='social_notifications' and policyname='notifications_owner_read'),'notification owner policy remains');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='message_attachments' and policyname='message_attachments_member_read'),'attachment member policy remains');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='online_guild_boss_rewards' and policyname='guild_boss_rewards_owner_read'),'Guild reward owner policy remains');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='love_space_events' and policyname='love_events_member_read'),'Love Space member policy remains');
select isnt_empty($$select 1 from pg_indexes where schemaname='public' and indexname='online_guild_one_leader'$$,'one-leader unique index remains');
select results_eq($$select count(*)::bigint from storage.buckets where id in('profile-photos','love-space-photos','chat-attachments') and public=false$$,array[3::bigint],'all Phase 4 buckets are private');
select * from finish();rollback;
