begin;
create extension if not exists pgtap with schema extensions;
select plan(18);
select has_table('public','achievement_definitions','achievement definitions exist');
select has_table('public','reward_ledger','reward ledger exists');
select has_table('public','user_cloud_wallets','cloud wallets exist');
select has_function('public','wallet_level_for_xp',array['bigint'],'level formula exists');
select has_function('public','apply_ledger_to_wallet','wallet materializer exists');
select has_function('public','ledger_from_productivity','productivity ledger hook exists');
select has_function('public','ledger_from_pvp_reward','pvp ledger hook exists');
select has_function('public','ledger_from_boss_reward','boss ledger hook exists');
select has_function('public','claim_achievement_reward_cloud',array['text','text'],'achievement claim RPC');
select has_function('public','wallet_balance','wallet balance RPC');
select has_function('public','admin_reverse_ledger',array['uuid','text'],'reversal RPC');
select col_is_unique('public','reward_ledger',array['user_id','idempotency_key'],'ledger is idempotent');
select has_trigger('public','productivity_events','productivity_to_ledger','productivity writes ledger');
select has_trigger('public','online_pvp_rewards','pvp_reward_to_ledger','pvp writes ledger');
select has_trigger('public','online_guild_boss_rewards','boss_reward_to_ledger','boss writes ledger');
select has_trigger('public','reward_ledger','reward_ledger_apply','ledger materializes wallet');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='reward_ledger' and policyname='reward_ledger_select_own'),'ledger RLS select own');
select ok(exists(select 1 from pg_policies where schemaname='public' and tablename='user_cloud_wallets' and policyname='user_cloud_wallets_select_own'),'wallet RLS select own');
select * from finish();
rollback;
