begin;
create extension if not exists pgtap with schema extensions;
select plan(29);
select has_table('public','conversations','conversations exists');
select has_table('public','conversation_members','conversation members exists');
select has_table('public','messages','messages exists');
select has_table('public','conversation_typing','typing state exists');
select has_table('public','user_presence','presence exists');
select has_table('public','social_notifications','notifications exist');
select has_table('public','productivity_events','productivity events exist');
select has_table('public','online_pvp_challenges','PvP exists');
select has_table('public','online_pvp_rewards','PvP rewards exist');
select has_table('public','online_guilds','online guilds exist');
select has_table('public','online_guild_members','online guild members exist');
select has_table('public','online_guild_messages','online guild messages exist');
select has_table('public','online_guild_battles','online guild battles exist');
select has_function('public','get_or_create_direct_conversation',array['uuid'],'DM RPC');
select has_function('public','send_direct_message',array['uuid','text','uuid'],'send DM RPC');
select has_function('public','set_conversation_typing',array['uuid','boolean'],'typing RPC');
select has_function('public','heartbeat_presence',array['text','text'],'presence RPC');
select has_function('public','record_productivity_event',array['text','text','text','timestamp with time zone','text','jsonb'],'productivity RPC');
select has_function('public','send_online_pvp_challenge',array['uuid','integer'],'PvP request RPC');
select has_function('public','respond_online_pvp_challenge',array['uuid','boolean'],'PvP response RPC');
select has_function('public','finalize_online_pvp',array['uuid'],'PvP finalizer RPC');
select has_function('public','create_online_guild',array['text','text'],'guild create RPC');
select has_function('public','request_online_guild_join',array['uuid'],'guild join RPC');
select has_function('public','send_online_guild_message',array['uuid','text','uuid'],'guild chat RPC');
select has_function('public','start_online_guild_boss',array['uuid','text','text','bigint'],'guild boss RPC');
select has_function('public','get_global_productivity_leaderboard',array['integer','integer'],'global leaderboard RPC');
select has_function('public','get_online_guild_leaderboard',array['integer'],'guild leaderboard RPC');
select col_is_unique('public','messages',array['sender_id','client_message_id'],'messages are idempotent');
select col_is_unique('public','productivity_events',array['user_id','idempotency_key'],'events are idempotent');
select * from finish();
rollback;
